<?php
/**
 * RenderrequestrestApi
 * PHP version 5
 *
 * @category Class
 * @package  Sunday\RenderClient
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Sunday Render Service
 *
 * Sunday Render Service
 *
 * OpenAPI spec version: 0.0.1-SNAPSHOT
 * Contact: molnar.balint@mdy.hu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Api;

use \Sunday\RenderClient\Configuration;
use \Sunday\RenderClient\ApiClient;
use \Sunday\RenderClient\ApiException;
use \Sunday\RenderClient\ObjectSerializer;

/**
 * RenderrequestrestApi Class Doc Comment
 *
 * @category Class
 * @package  Sunday\RenderClient
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RenderrequestrestApi
{

    /**
     * API Client
     *
     * @var \Sunday\RenderClient\ApiClient instance of the ApiClient
     */
    protected $apiClient;

    /**
     * Constructor
     *
     * @param \Sunday\RenderClient\ApiClient|null $apiClient The api client to use
     */
    public function __construct(\Sunday\RenderClient\ApiClient $apiClient = null)
    {
        if ($apiClient == null) {
            $apiClient = new ApiClient();
            $apiClient->getConfig()->setHost('https://sdy-as-01:8009/');
        }

        $this->apiClient = $apiClient;
    }

    /**
     * Get API client
     *
     * @return \Sunday\RenderClient\ApiClient get the API client
     */
    public function getApiClient()
    {
        return $this->apiClient;
    }

    /**
     * Set the API client
     *
     * @param \Sunday\RenderClient\ApiClient $apiClient set the API client
     *
     * @return RenderrequestrestApi
     */
    public function setApiClient(\Sunday\RenderClient\ApiClient $apiClient)
    {
        $this->apiClient = $apiClient;
        return $this;
    }

    /**
     * Operation renderRequestUsingPOST
     *
     * Handles a render request and returns
     *
     * @param \Swagger\Client\Model\RenderRequestEntity $render_request_entity renderRequestEntity (required)
     * @return string
     * @throws \Sunday\RenderClient\ApiException on non-2xx response
     */
    public function renderRequestUsingPOST($render_request_entity)
    {
        list($response) = $this->renderRequestUsingPOSTWithHttpInfo($render_request_entity);
        return $response;
    }

    /**
     * Operation renderRequestUsingPOSTWithHttpInfo
     *
     * Handles a render request and returns
     *
     * @param \Swagger\Client\Model\RenderRequestEntity $render_request_entity renderRequestEntity (required)
     * @return Array of string, HTTP status code, HTTP response headers (array of strings)
     * @throws \Sunday\RenderClient\ApiException on non-2xx response
     */
    public function renderRequestUsingPOSTWithHttpInfo($render_request_entity)
    {
        // verify the required parameter 'render_request_entity' is set
        if ($render_request_entity === null) {
            throw new \InvalidArgumentException('Missing the required parameter $render_request_entity when calling renderRequestUsingPOST');
        }
        // parse inputs
        $resourcePath = "/render";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = $this->apiClient->selectHeaderAccept(array('application/pdf'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(array('application/json;charset=UTF-8'));

        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        // body params
        $_tempBody = null;
        if (isset($render_request_entity)) {
            $_tempBody = $render_request_entity;
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'POST',
                $queryParams,
                $httpBody,
                $headerParams,
                'string',
                '/render'
            );

            return array($this->apiClient->getSerializer()->deserialize($response, 'string', $httpHeader), $statusCode, $httpHeader);
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), 'string', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }

}
