<?php
/**
 * PaymentRecordTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Sunday\ArchiveClient
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Sunday Archive Service
 *
 * Sunday Archive Service
 *
 * OpenAPI spec version: 0.0.1-SNAPSHOT
 * Contact: molnar.balint@mdy.hu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Sunday\ArchiveClient;

/**
 * PaymentRecordTest Class Doc Comment
 *
 * @category    Class */
// * @description PaymentRecord
/**
 * @package     Sunday\ArchiveClient
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PaymentRecordTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "PaymentRecord"
     */
    public function testPaymentRecord()
    {

    }

    /**
     * Test attribute "added_time"
     */
    public function testPropertyAddedTime()
    {

    }

    /**
     * Test attribute "backend_action_taken"
     */
    public function testPropertyBackendActionTaken()
    {

    }

    /**
     * Test attribute "extra_info"
     */
    public function testPropertyExtraInfo()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "initiator_application"
     */
    public function testPropertyInitiatorApplication()
    {

    }

    /**
     * Test attribute "last_updated_time"
     */
    public function testPropertyLastUpdatedTime()
    {

    }

    /**
     * Test attribute "payment_currency"
     */
    public function testPropertyPaymentCurrency()
    {

    }

    /**
     * Test attribute "payment_description"
     */
    public function testPropertyPaymentDescription()
    {

    }

    /**
     * Test attribute "payment_gateway_transaction_id"
     */
    public function testPropertyPaymentGatewayTransactionId()
    {

    }

    /**
     * Test attribute "payment_method"
     */
    public function testPropertyPaymentMethod()
    {

    }

    /**
     * Test attribute "payment_status"
     */
    public function testPropertyPaymentStatus()
    {

    }

    /**
     * Test attribute "payment_value"
     */
    public function testPropertyPaymentValue()
    {

    }

    /**
     * Test attribute "redirect_to"
     */
    public function testPropertyRedirectTo()
    {

    }

    /**
     * Test attribute "test_payment"
     */
    public function testPropertyTestPayment()
    {

    }

    /**
     * Test attribute "user_login_entity"
     */
    public function testPropertyUserLoginEntity()
    {

    }

}
