<?php
/**
 * RenderRequestEntityTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Sunday Render Service
 *
 * Sunday Render Service
 *
 * OpenAPI spec version: 0.0.1-SNAPSHOT
 * Contact: molnar.balint@mdy.hu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * RenderRequestEntityTest Class Doc Comment
 *
 * @category    Class */
// * @description RenderRequestEntity
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RenderRequestEntityTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "RenderRequestEntity"
     */
    public function testRenderRequestEntity()
    {

    }

    /**
     * Test attribute "document_type_id"
     */
    public function testPropertyDocumentTypeId()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "keywords"
     */
    public function testPropertyKeywords()
    {

    }

    /**
     * Test attribute "project_id"
     */
    public function testPropertyProjectId()
    {

    }

    /**
     * Test attribute "render_finished"
     */
    public function testPropertyRenderFinished()
    {

    }

    /**
     * Test attribute "render_requested"
     */
    public function testPropertyRenderRequested()
    {

    }

    /**
     * Test attribute "render_target"
     */
    public function testPropertyRenderTarget()
    {

    }

    /**
     * Test attribute "rendered_by"
     */
    public function testPropertyRenderedBy()
    {

    }

    /**
     * Test attribute "rendered_duration"
     */
    public function testPropertyRenderedDuration()
    {

    }

}
