<?php
/**
 * UserDataSaveRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Sunday\ArchiveClient
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Sunday Archive Service
 *
 * Sunday Archive Service
 *
 * OpenAPI spec version: 0.0.1-SNAPSHOT
 * Contact: molnar.balint@mdy.hu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Sunday\ArchiveClient;

/**
 * UserDataSaveRequestTest Class Doc Comment
 *
 * @category    Class */
// * @description UserDataSaveRequest
/**
 * @package     Sunday\ArchiveClient
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UserDataSaveRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "UserDataSaveRequest"
     */
    public function testUserDataSaveRequest()
    {

    }

    /**
     * Test attribute "birthday"
     */
    public function testPropertyBirthday()
    {

    }

    /**
     * Test attribute "birthplace"
     */
    public function testPropertyBirthplace()
    {

    }

    /**
     * Test attribute "company"
     */
    public function testPropertyCompany()
    {

    }

    /**
     * Test attribute "company_name"
     */
    public function testPropertyCompanyName()
    {

    }

    /**
     * Test attribute "company_tax_number"
     */
    public function testPropertyCompanyTaxNumber()
    {

    }

    /**
     * Test attribute "driver_license_number"
     */
    public function testPropertyDriverLicenseNumber()
    {

    }

    /**
     * Test attribute "first_name"
     */
    public function testPropertyFirstName()
    {

    }

    /**
     * Test attribute "home_address_id"
     */
    public function testPropertyHomeAddressId()
    {

    }

    /**
     * Test attribute "mail_address_id"
     */
    public function testPropertyMailAddressId()
    {

    }

    /**
     * Test attribute "marketing_accepted"
     */
    public function testPropertyMarketingAccepted()
    {

    }

    /**
     * Test attribute "mothers_birth_name"
     */
    public function testPropertyMothersBirthName()
    {

    }

    /**
     * Test attribute "personal_id_number"
     */
    public function testPropertyPersonalIdNumber()
    {

    }

    /**
     * Test attribute "phone"
     */
    public function testPropertyPhone()
    {

    }

    /**
     * Test attribute "sur_name"
     */
    public function testPropertySurName()
    {

    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {

    }

    /**
     * Test attribute "user_id"
     */
    public function testPropertyUserId()
    {

    }

}
