<?php
/**
 * FilerestApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Sunday\RenderService\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Sunday Render Service
 *
 * Sunday Render Service
 *
 * OpenAPI spec version: 0.0.1-SNAPSHOT
 * Contact: molnar.balint@mdy.hu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Sunday\RenderService\Client;

use \Sunday\RenderService\Client\Configuration;
use \Sunday\RenderService\Client\ApiClient;
use \Sunday\RenderService\Client\ApiException;
use \Sunday\RenderService\Client\ObjectSerializer;

/**
 * FilerestApiTest Class Doc Comment
 *
 * @category Class
 * @package  Sunday\RenderService\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class FilerestApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for createFileEntityUsingPOST
     *
     * Creates a file.
     *
     */
    public function testCreateFileEntityUsingPOST()
    {

    }

    /**
     * Test case for getFileEntityUsingGET
     *
     * Gets a file eneity, its metadata read from the database and its contents read from the file storage.
     *
     */
    public function testGetFileEntityUsingGET()
    {

    }

    /**
     * Test case for getFilesByProjectIdUsingGET
     *
     * Gets all file entities by a project. Note, that this operation only queries the database, and not the file contents..
     *
     */
    public function testGetFilesByProjectIdUsingGET()
    {

    }

    /**
     * Test case for updateFileContentsUsingPOST
     *
     * Updates a file.
     *
     */
    public function testUpdateFileContentsUsingPOST()
    {

    }

}
