<?php
/**
 * ProjectrestApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Sunday\RenderService\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Sunday Render Service
 *
 * Sunday Render Service
 *
 * OpenAPI spec version: 0.0.1-SNAPSHOT
 * Contact: molnar.balint@mdy.hu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Sunday\RenderService\Client;

use \Sunday\RenderService\Client\Configuration;
use \Sunday\RenderService\Client\ApiClient;
use \Sunday\RenderService\Client\ApiException;
use \Sunday\RenderService\Client\ObjectSerializer;

/**
 * ProjectrestApiTest Class Doc Comment
 *
 * @category Class
 * @package  Sunday\RenderService\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProjectrestApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for deleteProjectUsingDELETE
     *
     * Deletes a project, its document types, and its files..
     *
     */
    public function testDeleteProjectUsingDELETE()
    {

    }

    /**
     * Test case for getAllProjectsUsingGET
     *
     * Returns all projects.
     *
     */
    public function testGetAllProjectsUsingGET()
    {

    }

    /**
     * Test case for getProjectByIdUsingGET
     *
     * Gets a project by its ID.
     *
     */
    public function testGetProjectByIdUsingGET()
    {

    }

    /**
     * Test case for insertProjectUsingPOST
     *
     * Creates a new project. The ID does not need to be filled, as it is generated automatically.
     *
     */
    public function testInsertProjectUsingPOST()
    {

    }

    /**
     * Test case for updateProjectUsingPOST
     *
     * Updates a project..
     *
     */
    public function testUpdateProjectUsingPOST()
    {

    }

}
