<?php
/**
 * AllUsersPageResponse
 *
 * PHP version 5
 *
 * @category Class
 * @package  Sunday\ArchiveClient
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Sunday Archive Service
 *
 * Sunday Archive Service
 *
 * OpenAPI spec version: 0.0.1-SNAPSHOT
 * Contact: molnar.balint@mdy.hu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * AllUsersPageResponse Class Doc Comment
 *
 * @category    Class */
/** 
 * @package     Sunday\ArchiveClient
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AllUsersPageResponse implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'AllUsersPageResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = array(
        'all_entries' => 'int',
        'next_page_exists' => 'bool',
        'page_num' => 'int',
        'user_logins' => '\Swagger\Client\Model\UserLoginEntity[]'
    );

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = array(
        'all_entries' => 'allEntries',
        'next_page_exists' => 'nextPageExists',
        'page_num' => 'pageNum',
        'user_logins' => 'userLogins'
    );

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = array(
        'all_entries' => 'setAllEntries',
        'next_page_exists' => 'setNextPageExists',
        'page_num' => 'setPageNum',
        'user_logins' => 'setUserLogins'
    );

    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = array(
        'all_entries' => 'getAllEntries',
        'next_page_exists' => 'getNextPageExists',
        'page_num' => 'getPageNum',
        'user_logins' => 'getUserLogins'
    );

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = array();

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['all_entries'] = isset($data['all_entries']) ? $data['all_entries'] : null;
        $this->container['next_page_exists'] = isset($data['next_page_exists']) ? $data['next_page_exists'] : null;
        $this->container['page_num'] = isset($data['page_num']) ? $data['page_num'] : null;
        $this->container['user_logins'] = isset($data['user_logins']) ? $data['user_logins'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = array();
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        return true;
    }


    /**
     * Gets all_entries
     * @return int
     */
    public function getAllEntries()
    {
        return $this->container['all_entries'];
    }

    /**
     * Sets all_entries
     * @param int $all_entries Az összes felhasználó száma
     * @return $this
     */
    public function setAllEntries($all_entries)
    {
        $this->container['all_entries'] = $all_entries;

        return $this;
    }

    /**
     * Gets next_page_exists
     * @return bool
     */
    public function getNextPageExists()
    {
        return $this->container['next_page_exists'];
    }

    /**
     * Sets next_page_exists
     * @param bool $next_page_exists Van-e következő oldal?
     * @return $this
     */
    public function setNextPageExists($next_page_exists)
    {
        $this->container['next_page_exists'] = $next_page_exists;

        return $this;
    }

    /**
     * Gets page_num
     * @return int
     */
    public function getPageNum()
    {
        return $this->container['page_num'];
    }

    /**
     * Sets page_num
     * @param int $page_num Ennek az oldalnak a sorszáma
     * @return $this
     */
    public function setPageNum($page_num)
    {
        $this->container['page_num'] = $page_num;

        return $this;
    }

    /**
     * Gets user_logins
     * @return \Swagger\Client\Model\UserLoginEntity[]
     */
    public function getUserLogins()
    {
        return $this->container['user_logins'];
    }

    /**
     * Sets user_logins
     * @param \Swagger\Client\Model\UserLoginEntity[] $user_logins Felhasználók listája
     * @return $this
     */
    public function setUserLogins($user_logins)
    {
        $this->container['user_logins'] = $user_logins;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Sunday\ArchiveClient\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Sunday\ArchiveClient\ObjectSerializer::sanitizeForSerialization($this));
    }
}


